"""
Django settings for ECHOME project.
Generated by 'django-admin startproject'.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# -----------------------------------------
# BASE DIR & ENVIRONMENT VARIABLES
# -----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path, override=True)

# Django secret key
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-default-key")

# Debug mode
# DEBUG = os.getenv("DEBUG", "False") == "True"
DEBUG = False

# Allowed hosts
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS")
custom_host = os.getenv("CUSTOM_HOST")

ALLOWED_HOSTS = [
    "echome.work.gd",
    "www.echome.work.gd",
    "13.203.229.52",
    "127.0.0.1",
    "localhost",
    f"{custom_host}",
]


# -----------------------------------------
# BLOCKCHAIN CONFIG
# -----------------------------------------
PRIVATE_KEY = os.getenv("PRIVATE_KEY")
WALLET_ADDRESS = os.getenv("WALLET_ADDRESS")
RPC_ENDPOINT = os.getenv("RPC_URL")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS")
CHAIN_ID = os.getenv("CHAIN_ID")

# -----------------------------------------
# FILEBASE / STORAGE CONFIG
# -----------------------------------------
FILEBASE_KEY = os.getenv("FILEBASE_KEY")
FILEBASE_SECRET = os.getenv("FILEBASE_SECRET")
BUCKET_NAME = os.getenv("BUCKET_NAME")

# -----------------------------------------
# SMTP EMAIL CONFIG (GMAIL or ANY)
# -----------------------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"  # prints emails in console
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")

GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")  # legacy support

# -----------------------------------------
# APPLICATIONS
# -----------------------------------------
INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Your apps
    "accounts",     # custom User model + auth
    "worker",
    "ECHOME",
]

SITE_ID = 1  # Required for allauth

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------
# MIDDLEWARE
# -----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',   #
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'accounts.middleware.CustomAuthMiddleware',
    # ← all-auth wants this

]

ROOT_URLCONF = "ECHOME.urls"

# -----------------------------------------
# TEMPLATES
# -----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "ECHOME.wsgi.application"

# -----------------------------------------
# DATABASE
# -----------------------------------------
from urllib.parse import urlparse, parse_qsl

tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.name.decode() if isinstance(tmpPostgres.name, bytes) else tmpPostgres.name.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# -----------------------------------------
# AUTHENTICATION & CUSTOM USER MODEL
# -----------------------------------------
AUTH_USER_MODEL = "accounts.User"# Use default User model; change to "accounts.User" if using custom model


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "accounts.auth_backend.EmailOrUsernameBackend"
]


ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"   # set "mandatory" in production
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm"
}

# -----------------------------------------
# PASSWORD VALIDATORS
# -----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------------------
# STATIC FILES
# -----------------------------------------
STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# -----------------------------------------
# SCHEDULER CONFIG
# -----------------------------------------
# SCHEDULER_CONFIG = {
#     "executors": {
#         "default": {"type": "threadpool", "max_workers": 10},
#         "processpool": {"type": "processpool", "max_workers": 5},
#     },
#     "job_defaults": {
#         "coalesce": False,
#         "max_instances": 3,
#     },
# }
#
# APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

# -----------------------------------------
# LOGGING
# -----------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "scheduler.log",
        },
    },
    "loggers": {
        "worker": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# -----------------------------------------
# SECURITY (turn ON in production)
# -----------------------------------------
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = False
X_FRAME_OPTIONS = "DENY"

# Celery / Redis
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Optional: json serialization to avoid pickle
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Beat schedule — run send_notification every 60 seconds
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "check-expired-capsules-every-1-min": {
        "task": "worker.tasks.run_send_notification",
        "schedule": 60.0,
    },
}
LOGIN_URL = 'account:login'
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'account:login'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id':os.getenv("GOOGLE_CLIENT_ID"),
            'secret':os.getenv("GOOGLE_CLIENT_SECRET"),
            'key': ""
        }
    }
}

SESSION_SECRET_KEY = os.getenv("SESSION_SECRET_KEY")
SESSION_COOKIE_NAME ="XSESSIONID"
CUSTOM_SESSION_COOKIE = SESSION_COOKIE_NAME
SESSION_TTL_SECONDS = 7 * 24 * 3600  # 7 days


MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"


CELERY_ACCEPT_CONTENT = [ 'json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

REDIS_URL = os.getenv("REDIS_URL")

CELERY_BROKER_URL = f"{REDIS_URL}"
CELERY_RESULT_BACKEND = f"{REDIS_URL}"