[supervisord]
nodaemon=true

[program:migrations]
command=python manage.py migrate
directory=/app
autorestart=false
priority=1

[program:gunicorn]
command=gunicorn ECHOME.wsgi:application --bind 0.0.0.0:8000 --workers 3
directory=/app
autorestart=true
priority=10

[program:celery_worker]
command=celery -A ECHOME worker -l info
directory=/app
autorestart=true
priority=20

[program:celery_beat]
command=celery -A ECHOME beat -l info
directory=/app
autorestart=true
priority=30
