# Generated by Django 4.2.19 on 2025-11-29 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faildedloginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faildedloginattempt',
            name='faildedLoginAttempts',
        ),
        migrations.RemoveField(
            model_name='faildedloginattempt',
            name='freezed_till',
        ),
        migrations.AddField(
            model_name='user',
            name='faildedLoginAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='freezed_till',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
