# Generated by Django 4.2.19 on 2025-11-29 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_faildedloginattempt_faildedloginattempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='freezed_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
