# Generated by Django 4.2.20 on 2025-09-25 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cid', models.CharField(max_length=255)),
                ('decryption_pass', models.CharField(max_length=255)),
                ('storage_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('unlock_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'TimeCapsule',
            },
        ),
    ]
