# Generated by Django 4.2.19 on 2025-12-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
            ],
            options={
                'db_table': 'file_storage',
            },
        ),
        migrations.CreateModel(
            name='TimeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cid', models.CharField(max_length=255)),
                ('decryption_pass', models.CharField(max_length=255)),
                ('storage_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('unlock_time', models.IntegerField(default=0)),
                ('file_ext', models.CharField(default='txt', max_length=10)),
                ('file_mime', models.CharField(default='text/plain', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TimeCapsule',
            },
        ),
    ]
