# Generated by Django 4.2.19 on 2025-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECHOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='unlock_time',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
