# Generated by Django 4.2.19 on 2025-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECHOME', '0002_timecapsule_unlock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='unlock_time',
            field=models.IntegerField(default=0),
        ),
    ]
